AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 90

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Disabled cops
Style/FrozenStringLiteralComment:
  Enabled: false
