AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 90
  Exclude:
    - "spec/**/*_spec.rb"

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/CaseIndentation:
  EnforcedStyle: end
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/WordArray:
  EnforcedStyle: brackets

# Disabled cops
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false