- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: 6288774
  cosine_coefficient: -20905355
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: 1274027
  cosine_coefficient: -3699111
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: 658314
  cosine_coefficient: -2955968
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 0
  sine_coefficient: 213618
  cosine_coefficient: -569925
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: -185116
  cosine_coefficient: 48888
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  sine_coefficient: -114332
  cosine_coefficient: -3149
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: 58793
  cosine_coefficient: 246158
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: 57066
  cosine_coefficient: -152138
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: 53322
  cosine_coefficient: -170733
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: 45758
  cosine_coefficient: -204586
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: -40923
  cosine_coefficient: -129620
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: -34720
  cosine_coefficient: 108743
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: -30383
  cosine_coefficient: 104755
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -2
  sine_coefficient: 15327
  cosine_coefficient: 10321
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  sine_coefficient: -12528
  cosine_coefficient: null
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -2
  sine_coefficient: 10980
  cosine_coefficient: 79661
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: 10675
  cosine_coefficient: -34782
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 3
  moon_argument_of_latitude: 0
  sine_coefficient: 10034
  cosine_coefficient: -23210
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: 8548
  cosine_coefficient: -21636
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: -7888
  cosine_coefficient: 24208
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: -6766
  cosine_coefficient: 30824
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: -5163
  cosine_coefficient: -8379
- moon_mean_elongation: 1
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: 4987
  cosine_coefficient: -16675
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: 4036
  cosine_coefficient: -12831
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 0
  sine_coefficient: 3994
  cosine_coefficient: -10445
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: 3861
  cosine_coefficient: -11650
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -3
  moon_argument_of_latitude: 0
  sine_coefficient: 3665
  cosine_coefficient: 14403
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: -2689
  cosine_coefficient: -7003
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 2
  sine_coefficient: -2602
  cosine_coefficient: null
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: 2390
  cosine_coefficient: 10056
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: -2348
  cosine_coefficient: 6322
- moon_mean_elongation: 2
  sun_mean_anomaly: -2
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: 2236
  cosine_coefficient: -9884
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 0
  sine_coefficient: -2120
  cosine_coefficient: 5751
- moon_mean_elongation: 0
  sun_mean_anomaly: 2
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: -2069
  cosine_coefficient: null
- moon_mean_elongation: 2
  sun_mean_anomaly: -2
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: 2048
  cosine_coefficient: -4950
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -2
  sine_coefficient: -1773
  cosine_coefficient: 4130
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  sine_coefficient: -1595
  cosine_coefficient: null
- moon_mean_elongation: 4
  sun_mean_anomaly: -1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: 1215
  cosine_coefficient: -3958
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 2
  sine_coefficient: -1110
  cosine_coefficient: null
- moon_mean_elongation: 3
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: -892
  cosine_coefficient: 3258
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: -810
  cosine_coefficient: 2616
- moon_mean_elongation: 4
  sun_mean_anomaly: -1
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: 759
  cosine_coefficient: -1897
- moon_mean_elongation: 0
  sun_mean_anomaly: 2
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: -713
  cosine_coefficient: -2117
- moon_mean_elongation: 2
  sun_mean_anomaly: 2
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: -700
  cosine_coefficient: 2354
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: 691
  cosine_coefficient: null
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -2
  sine_coefficient: 596
  cosine_coefficient: null
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: 549
  cosine_coefficient: -1423
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 4
  moon_argument_of_latitude: 0
  sine_coefficient: 537
  cosine_coefficient: -1117
- moon_mean_elongation: 4
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  sine_coefficient: 520
  cosine_coefficient: -1571
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: -487
  cosine_coefficient: -1739
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -2
  sine_coefficient: -399
  cosine_coefficient: null
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: -2
  sine_coefficient: -381
  cosine_coefficient: -4421
- moon_mean_elongation: 1
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: 351
  cosine_coefficient: null
- moon_mean_elongation: 3
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  sine_coefficient: -340
  cosine_coefficient: null
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: -3
  moon_argument_of_latitude: 0
  sine_coefficient: 330
  cosine_coefficient: null
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 0
  sine_coefficient: 327
  cosine_coefficient: null
- moon_mean_elongation: 0
  sun_mean_anomaly: 2
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  sine_coefficient: -323
  cosine_coefficient: 1165
- moon_mean_elongation: 1
  sun_mean_anomaly: 1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  sine_coefficient: 299
  cosine_coefficient: null
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 3
  moon_argument_of_latitude: 0
  sine_coefficient: 294
  cosine_coefficient: null
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -2
  sine_coefficient: null
  cosine_coefficient: 8752
