- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -171996
  sine_coefficient_second_term: -174.2
  cosine_coefficient_first_term: 92025
  cosine_coefficient_second_term: 8.9
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -13187
  sine_coefficient_second_term: -1.6
  cosine_coefficient_first_term: 5736
  cosine_coefficient_second_term: -3.1
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -2274
  sine_coefficient_second_term: -0.2
  cosine_coefficient_first_term: 977
  cosine_coefficient_second_term: -0.5
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: 2062
  sine_coefficient_second_term: 0.2
  cosine_coefficient_first_term: -895
  cosine_coefficient_second_term: 0.5
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 1426
  sine_coefficient_second_term: -3.4
  cosine_coefficient_first_term: 54
  cosine_coefficient_second_term: -0.1
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 712
  sine_coefficient_second_term: 0.1
  cosine_coefficient_first_term: -7
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -517
  sine_coefficient_second_term: 1.2
  cosine_coefficient_first_term: 224
  cosine_coefficient_second_term: -0.6
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -386
  sine_coefficient_second_term: -0.4
  cosine_coefficient_first_term: 200
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -301
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 129
  cosine_coefficient_second_term: -0.1
- moon_mean_elongation: -2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: 217
  sine_coefficient_second_term: -0.5
  cosine_coefficient_first_term: -95
  cosine_coefficient_second_term: 0.3
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -158
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 129
  sine_coefficient_second_term: 0.1
  cosine_coefficient_first_term: -70
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: 123
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -53
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 63
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 63
  sine_coefficient_second_term: 0.1
  cosine_coefficient_first_term: -33
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -59
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 26
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -58
  sine_coefficient_second_term: -0.1
  cosine_coefficient_first_term: 32
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -51
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 27
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 48
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 46
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -24
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -38
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 16
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -31
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 13
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 29
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: 29
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -12
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 26
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -22
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 21
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -10
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 2
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 17
  sine_coefficient_second_term: -0.1
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 16
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -8
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 2
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -16
  sine_coefficient_second_term: 0.1
  cosine_coefficient_first_term: 7
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -15
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 9
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -13
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 7
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -12
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 6
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: -2
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 11
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -10
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 5
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -8
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: 7
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -7
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -7
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -7
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 6
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: 6
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 6
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: -3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -6
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -6
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: -1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 5
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -5
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -5
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: -5
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 3
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 4
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 1
  sine_coefficient_first_term: 4
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -2
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 4
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -4
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -4
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -4
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: 3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: -1
  sun_mean_anomaly: -1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 0
  longitude_of_ascending_node: 0
  sine_coefficient_first_term: -3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: -1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 3
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 2
  longitude_of_ascending_node: 2
  sine_coefficient_first_term: -3
  sine_coefficient_second_term: 0
  cosine_coefficient_first_term: 0
  cosine_coefficient_second_term: 0
