- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: 5128122
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 1
  sine_coefficient: 280602
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -1
  sine_coefficient: 277693
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: 173237
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 1
  sine_coefficient: 55413
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -1
  sine_coefficient: 46271
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: 32573
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 1
  sine_coefficient: 17198
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -1
  sine_coefficient: 9266
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: -1
  sine_coefficient: 8822
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: 8216
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: -1
  sine_coefficient: 4324
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 1
  sine_coefficient: 4200
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: -3359
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 1
  sine_coefficient: 2463
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: 2211
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -1
  sine_coefficient: 2065
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -1
  sine_coefficient: -1870
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -1
  sine_coefficient: 1828
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: -1794
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 3
  sine_coefficient: -1749
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 1
  sine_coefficient: -1565
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: -1491
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 1
  sine_coefficient: -1475
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -1
  sine_coefficient: -1410
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: -1344
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: -1335
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 3
  moon_argument_of_latitude: 1
  sine_coefficient: 1107
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: 1021
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 1
  sine_coefficient: 833
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -3
  sine_coefficient: 777
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 1
  sine_coefficient: 671
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -3
  sine_coefficient: 607
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: -1
  sine_coefficient: 596
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -1
  sine_coefficient: 491
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: 1
  sine_coefficient: -451
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 3
  moon_argument_of_latitude: -1
  sine_coefficient: 439
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 1
  sine_coefficient: 422
- moon_mean_elongation: 2
  sun_mean_anomaly: 0
  moon_mean_anomaly: -3
  moon_argument_of_latitude: -1
  sine_coefficient: 421
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: 1
  sine_coefficient: -366
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: -351
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: 331
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 1
  sine_coefficient: 315
- moon_mean_elongation: 2
  sun_mean_anomaly: -2
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: 302
- moon_mean_elongation: 0
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 3
  sine_coefficient: -283
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -1
  sine_coefficient: -229
- moon_mean_elongation: 1
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: 223
- moon_mean_elongation: 1
  sun_mean_anomaly: 1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: 223
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: -2
  moon_argument_of_latitude: -1
  sine_coefficient: -220
- moon_mean_elongation: 2
  sun_mean_anomaly: 1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -1
  sine_coefficient: -220
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: 1
  sine_coefficient: -185
- moon_mean_elongation: 2
  sun_mean_anomaly: -1
  moon_mean_anomaly: -2
  moon_argument_of_latitude: -1
  sine_coefficient: 181
- moon_mean_elongation: 0
  sun_mean_anomaly: 1
  moon_mean_anomaly: 2
  moon_argument_of_latitude: 1
  sine_coefficient: -177
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: -2
  moon_argument_of_latitude: -1
  sine_coefficient: 176
- moon_mean_elongation: 4
  sun_mean_anomaly: -1
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -1
  sine_coefficient: 166
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -1
  sine_coefficient: -164
- moon_mean_elongation: 4
  sun_mean_anomaly: 0
  moon_mean_anomaly: 1
  moon_argument_of_latitude: -1
  sine_coefficient: 132
- moon_mean_elongation: 1
  sun_mean_anomaly: 0
  moon_mean_anomaly: -1
  moon_argument_of_latitude: -1
  sine_coefficient: -119
- moon_mean_elongation: 4
  sun_mean_anomaly: -1
  moon_mean_anomaly: 0
  moon_argument_of_latitude: -1
  sine_coefficient: 115
- moon_mean_elongation: 2
  sun_mean_anomaly: -2
  moon_mean_anomaly: 0
  moon_argument_of_latitude: 1
  sine_coefficient: 107
